### ISSUE TITLE
Still stuck at "Loading parcel data" after update

### ISSUE THREAD

**Issue by RC-Thoughts** [jesmak/MMM-FinParcel#2]
Still stuck at "Loading parcel data" even after update. MagicMirror is connecting o oma.posti.fi according my DNS-server, no blocked queries so everything is ok on the network side. Oma.posti.fi is opening normally from browser.

I minimized config to narrow possible typo's in translations etc:

`{

                    module: "MMM-FinParcel",
                    header: "Posti Online",
                    position: "top_right",
                    config: {
                        postiUserName: 'user@domain',
                        postiPassword: 'password',
                        limit: '5',
                        updateInterval: '30',
                        showDeliveredDays: '2',
                        language: 'fi'
                    }
        },`

Ideas what to check?

**Comment by jesmak** [comment]
Do you have Matkahuolto configured? If not, I suppose there's another bug
regarding this. I'll check the code and probably do another fix today.

ti 29. syysk. 2020 klo 16.35 Tero @RC-Thoughts.com <notifications@github.com>
kirjoitti:

**Comment by RC-Thoughts** [comment]
No Matkahuolto is used. No hurry, just glad to get this sorted, great plugin!

**Comment by jesmak** [comment]
I tested without Matkahuolto configured, and it seems to work just fine, so that is not the issue here. Could you open your MagicMirror UI to a web browser and check the console output? The plugin ouputs some debug info there which could be useful. You should see something like this if everything works properly:

MMM-FinParcel.js:57 Update notification received
MMM-FinParcel.js:57 Updating Posti parcels...
MMM-FinParcel.js:57 Authenticating to Posti API
MMM-FinParcel.js:57 Loading parcel data from Posti API
MMM-FinParcel.js:57 Parcel data loaded from Posti API
MMM-FinParcel.js:57 Sending update notification to UI

**Comment by RC-Thoughts** [comment]
Cool, didn't know about that one. Here's the output, it looks like the connection to Posti is ok but parsing or showing the data fails or screen is not updated:

`
Load script: modules/MMM-FinParcel//MMM-FinParcel.js module.js:486
Module registered: MMM-FinParcel loader.js:147 
Bootstrapping module: MMM-FinParcel loader.js:235
File already loaded: moment.js loader.js:152
Scripts loaded for: MMM-FinParcel loader.js:235
File already loaded: font-awesome.css loader.js:194
Load stylesheet: modules/MMM-FinParcel/MMM-FinParcel.css loader.js:154
Styles loaded for: MMM-FinParcel loader.js:156
Translations loaded for: MMM-FinParcel loader.js:175

MMM-FinParcel.js:57 Update notification received
MMM-FinParcel.js:57 Updating Posti parcels...
MMM-FinParcel.js:57 Authenticating to Posti API
MMM-FinParcel.js:57 Loading parcel data from Posti API
MMM-FinParcel.js:57 Parcel data loaded from Posti API
`

**Comment by RC-Thoughts** [comment]
I removed all other modules from use, same thing, I changed to "updateInterval: "1"," can follow the console and see the updating is done but for some reason the drawing of screen is not done.

**Comment by thapster** [comment]
I have same problem and mm-error.log says following:
[2020-10-13 13:50:08.600] [ERROR]  Whoops! There was an uncaught exception...
[2020-10-13 13:50:08.605] [ERROR]  TypeError: Cannot read property 'name' of undefined
    at /home/pi/MagicMirror/modules/MMM-FinParcel/node_helper.js:101:57
    at Array.map (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-FinParcel/node_helper.js:99:47)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-FinParcel/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-FinParcel/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-FinParcel/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
